name: ac_sampler
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.8
  - pip
  - numpy>=1.20
  - click>=8.0
  - pillow>=8.3.1
  - scipy>=1.7.1
  - pytorch=1.12.1
  - torchvision=0.13.1
  - cudatoolkit=11.3
  - requests
  - tqdm
  - pip:
    - sortedcontainers
